name: hwm48
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  path_provider: ^2.1.1
  path: ^1.8.3
  flutter_slidable: ^3.0.1
  collection: ^1.17.2
  auto_size_text: ^3.0.0
  freezed_annotation:
  json_annotation: ^4.8.1
  loading_animation_widget: ^1.2.0+4
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  device_info_plus: ^9.1.1
  drift: ^2.14.1
  sqlite3: ^2.3.0
  sqlite3_flutter_libs: ^0.5.18
  bloc_concurrency: ^0.2.3



dev_dependencies:
  drift_dev: ^2.14.0
  freezed:
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Lemon
      fonts:
        - asset: assets/fonts/Lemon/Lemon-Regular.ttf
